"""empty message

Revision ID: 1277de63cbcf
Revises: 224ee9d801a3
Create Date: 2026-03-09 14:30:09.064101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1277de63cbcf'
down_revision = '224ee9d801a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stu_course', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('stu_course')

    # ### end Alembic commands ###
