"""add stu_address column

Revision ID: 224ee9d801a3
Revises: 4b66d2564494
Create Date: 2026-03-06 16:58:47.250812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '224ee9d801a3'
down_revision = '4b66d2564494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stu_address', sa.String(length=100), nullable=False))
        batch_op.alter_column('stu_age',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('stu_phone',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('stu_phone',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('stu_age',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('stu_address')

    # ### end Alembic commands ###
